#pragma once
static const uint32_t WEATHER_ICONS[] = {
  RESOURCE_ID_ICON_CLEAR_DAY,
  RESOURCE_ID_ICON_CLEAR_NIGHT,
  RESOURCE_ID_ICON_WIND,
  RESOURCE_ID_ICON_COLD,
  RESOURCE_ID_ICON_HOT,
  RESOURCE_ID_ICON_PARTLY_CLOUDY_DAY,
  RESOURCE_ID_ICON_PARTLY_CLOUDY_NIGHT,
  RESOURCE_ID_ICON_FOG,
  RESOURCE_ID_ICON_RAIN,
  RESOURCE_ID_ICON_SNOW,
  RESOURCE_ID_ICON_SLEET, //This is really "Hail""
  RESOURCE_ID_ICON_SNOW_SLEET, //This is really "Snow/Hail"
  RESOURCE_ID_ICON_RAIN_SLEET, //This is really "Rain/Hail"
  RESOURCE_ID_ICON_RAIN_SNOW, //This is "Sleet"
  RESOURCE_ID_ICON_CLOUDY,
  RESOURCE_ID_ICON_THUNDER,
  RESOURCE_ID_ICON_NOT_AVAILABLE,
  RESOURCE_ID_ICON_DRIZZLE,
}; 

static const uint32_t WEATHER_ICONS_SMALL[] = {
  RESOURCE_ID_ICON_CLEAR_DAY_SMALL,
  RESOURCE_ID_ICON_CLEAR_NIGHT_SMALL,
  RESOURCE_ID_ICON_WIND_SMALL,
  RESOURCE_ID_ICON_COLD_SMALL,
  RESOURCE_ID_ICON_HOT_SMALL,
  RESOURCE_ID_ICON_PARTLY_CLOUDY_DAY_SMALL,
  RESOURCE_ID_ICON_PARTLY_CLOUDY_NIGHT_SMALL,
  RESOURCE_ID_ICON_FOG_SMALL,
  RESOURCE_ID_ICON_RAIN_SMALL,
  RESOURCE_ID_ICON_SNOW_SMALL,
  RESOURCE_ID_ICON_SLEET_SMALL,
  RESOURCE_ID_ICON_SNOW_SLEET_SMALL,
  RESOURCE_ID_ICON_RAIN_SLEET_SMALL,
  RESOURCE_ID_ICON_RAIN_SNOW_SMALL,
  RESOURCE_ID_ICON_CLOUDY_SMALL,
  RESOURCE_ID_ICON_THUNDER_SMALL,
  RESOURCE_ID_ICON_NOT_AVAILABLE_SMALL,
  RESOURCE_ID_ICON_DRIZZLE_SMALL,
  RESOURCE_ID_DISCONNECTED,
}; 
